exclude: "node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            files: "crm.*"
            exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
          - id: no-commit-to-branch
            args: ["--branch", "develop"]
          - id: check-merge-conflict
          - id: check-ast
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: debug-statements

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            types_or: [javascript, ts, vue, css, scss]
            # Ignore frontend folder and any files that might contain jinja / bundles
            exclude: |
                (?x)^(
                    frontend/.*|
                    crm/public/dist/.*|
                    .*node_modules.*|
                    .*boilerplate.*|
                    crm/templates/includes/.*|
                )$

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.1
      hooks:
          - id: ruff
            name: "Run ruff linter and apply fixes"
            args: ["--fix"]

          - id: ruff-format
            name: "Run ruff formatter"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
